spring.application.name=school

spring.datasource.url=jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Le mode "update" dit à Hibernate de créer automatiquement les tables manquantes ou de modifier les colonnes existantes sans effacer tes données.
spring.jpa.hibernate.ddl-auto=update

# Permet d'afficher les requêtes SQL générées par Spring dans ta console IntelliJ (Super utile pour comprendre ce qu'il fait sous le capot !)
spring.jpa.show-sql=true

# Force l'utilisation du langage SQL spécifique à MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
